# Generated by Django 2.0.4 on 2018-07-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Badge_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('dateOfJoining', models.DateField()),
                ('highestScoutingQualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scout_Proficiency_Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPassing', models.DateField()),
                ('certificateNo', models.CharField(max_length=4)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Scout')),
            ],
        ),
        migrations.CreateModel(
            name='Scout_Ranked_Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPassing', models.DateField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Scout')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='scout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Section'),
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Badge_Category'),
        ),
    ]
