# Generated by Django 2.0.4 on 2018-07-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0003_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout_proficiency_badge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Badge'),
        ),
        migrations.AlterField(
            model_name='scout_ranked_badge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Badge'),
        ),
    ]
