# Generated by Django 2.0.4 on 2018-07-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0004_auto_20180708_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout_proficiency_badge',
            name='scout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Scout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scout_ranked_badge',
            name='scout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Scout'),
            preserve_default=False,
        ),
    ]
