# Generated by Django 2.0.4 on 2018-07-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0005_auto_20180708_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scout',
            name='dateOfBirth',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='dateOfJoining',
            field=models.DateField(verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='highestScoutingQualification',
            field=models.CharField(max_length=50, verbose_name='Highest Scout Qualification'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
