# Generated by Django 2.0.4 on 2018-07-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0006_auto_20180711_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Section'),
            preserve_default=False,
        ),
    ]
