# Generated by Django 2.0.4 on 2018-07-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0008_group_user_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_user',
            name='section',
        ),
    ]
