# Generated by Django 2.0.4 on 2018-07-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0011_scout_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout_proficiency_badge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='scout_proficiency_badge',
            name='scout',
        ),
        migrations.RemoveField(
            model_name='scout_ranked_badge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='scout_ranked_badge',
            name='scout',
        ),
        migrations.AddField(
            model_name='section',
            name='prerequisite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boyScouts.Section'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('PB', 'Proficiency Badge'), ('RB', 'Rank Badge')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Scout_Proficiency_Badge',
        ),
        migrations.DeleteModel(
            name='Scout_Ranked_Badge',
        ),
    ]
