# Generated by Django 2.0.4 on 2018-07-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0012_auto_20180723_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPassing', models.DateField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Badge')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyScouts.Scout')),
            ],
        ),
    ]
