# Generated by Django 2.0.4 on 2018-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0014_auto_20180724_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scout_rank_badge',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
