# Generated by Django 2.0.4 on 2018-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0015_auto_20180729_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='scout_proficiency_badge',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
