# Generated by Django 2.0.4 on 2018-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0017_auto_20180729_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout_proficiency_badge',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scout_rank_badge',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
