# Generated by Django 2.1 on 2018-08-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0018_auto_20180729_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout_proficiency_badge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boyScouts.Badge'),
        ),
        migrations.AlterField(
            model_name='scout_rank_badge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boyScouts.Badge'),
        ),
        migrations.AlterField(
            model_name='section',
            name='prerequisite',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boyScouts.Section'),
        ),
    ]
