# Generated by Django 2.1 on 2018-08-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0019_auto_20180805_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='prerequisite',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boyScouts.Section'),
        ),
    ]
