# Generated by Django 2.1 on 2018-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0020_auto_20180805_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout_proficiency_badge',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scout_rank_badge',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
    ]
