# Generated by Django 2.1 on 2018-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0021_auto_20180805_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout_proficiency_badge',
            name='approval_required',
        ),
        migrations.RemoveField(
            model_name='scout_rank_badge',
            name='approval_required',
        ),
        migrations.AddField(
            model_name='badge',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
    ]
