# Generated by Django 2.1 on 2018-08-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0022_auto_20180805_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='cnic',
            field=models.CharField(default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scout',
            name='cnicId',
            field=models.CharField(default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scout',
            name='imageId',
            field=models.CharField(default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scout',
            name='image',
            field=models.CharField(default='a', max_length=2000),
            preserve_default=False,
        ),
    ]
