# Generated by Django 2.1 on 2018-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyScouts', '0023_auto_20180809_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='cnic',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='scout',
            name='cnicId',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='scout',
            name='image',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='scout',
            name='imageId',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
